version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: hacker_news
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
  api:
    container_name: api_server
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
  client:
    container_name: client
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client:/app

